#!/bin/sh
cd ~
mkdir src bin planet
cd ~/planet
wget https://github.com/ParveenArora/MeraMap/blob/master/osm_data_file/ludhiana.osm.bz2
 
sudo cp /etc/postgresql/8.4/main/postgresql.conf postgredql_original.conf
#sudo /etc/postgresql/8.4/main/cat postgresql.conf | sed  '/shared_buffers/s/24/128/g' postgresql.conf > postgresql
#mv postgresql postgresql.conf
#sudo /etc/postgresql/8.4/main/cat postgresql.conf | sed  '/checkpoint_segments/s/
#24/128/g' postgresql.conf > postgresql
#mv postgresql postgresql.conf

wget https://github.com/ParveenArora/MeraMap/blob/master/configuration_files/default_postgresql.conf

#echo "Difference in files"
#diff /etc/postgresql/8.4/main/postgresql.conf default_postgresql.conf

echo "Creating patch....... "
diff -u /etc/postgresql/8.4/main/postgresql.conf postgresql.conf > postgresql.patch

echo "Apply patch.......... "
patch postgresql.conf < postgresql.patch
echo "Done"
echo "Change are made in original File"


sudo sh -c "echo 'kernel.shmmax=268435456' > /etc/sysctl.d/60-shmmax.conf"
sudo service procps start

sudo /etc/init.d/postgresql-8.4 restart

sudo -u postgres -i
createuser username # answer yes for superuser
createdb -E UTF8 -O username gis
createlang plpgsql gis
exit 

psql -f /usr/share/postgresql/8.4/contrib/postgis-1.5/postgis.sql -d gis
echo "ALTER TABLE geometry_columns OWNER TO username; ALTER TABLE spatial_ref_sys OWNER TO username;" | psql -d gis

psql -f /usr/share/postgresql/8.4/contrib/_int.sql -d gis
psql -f ~/bin/osm2pgsql/900913.sql -d gis

osm2pgsql -S /usr/share/osm2pgsql/osm2pgsql/default.style --slim -d gis -C 2048 ~/planet/india.osm.bz2
mkdir world_boundaries

cd ~/bin
svn co http://svn.openstreetmap.org/applications/rendering/mapnik
cd ~/bin/mapnik
mkdir world_boundaries
wget http://202.164.53.116/~parveen/wb/10m-populated-places.zip
wget http://202.164.53.116/~parveen/wb/110m-admin-0-boundary-lines.zip
wget http://202.164.53.116/~parveen/wb/world_boundaries-spherical.tgz
tar xvzf world_boundaries-spherical.tgz
unzip 10m-populated-places.zip -d world_boundaries
unzip 110m-admin-0-boundary-lines.zip -d world_boundaries
cd ~/bin/mapnik
rm generate_image.py
wget https://github.com/ParveenArora/MeraMap/blob/master/configuration_files/generate_image.py
sudo ldconfig
cd ~/bin/mapnik
./generate_xml.py --dbname gis --user username --accept-none
./generate_image.py



