#!/bin/bash
source variables.sh

if [ -e $MERAMAP/$LOGFILE_OSM2PGSQL ]; then rm $MERAMAP/$LOGFILE_OSM2PGSQL; fi
echo $0 >> $MERAMAP/$LOGFILE_OSM2PGSQL 2>&1

if [ -f $MERAMAP/$FILE_DEFAULT_STYLE ];
then
    echo "File exists" >> $MERAMAP/$LOGFILE_OSM2PGSQL 2>&1
    osm2pgsql -S $MERAMAP/$FILE_DEFAULT_STYLE --slim -d $DBNAME -C 2048 $MERAMAP/$FILE_OSMDATAFILE >> $MERAMAP/$LOGFILE_OSM2PGSQL 2>&1
else
    osm2pgsql -S $MERAMAP/$FILE_DEFAULT_FILE_STYLE --slim -d $DBNAME -C 2048 $MERAMAP/$FILE_OSMDATAFILE >> $MERAMAP/$LOGFILE_OSM2PGSQL 2>&1
fi
