#!/bin/bash
source variables.sh
if [ -e $LOGFILE_INST ]; then rm $LOGFILE_INST; fi

echo $0 >> $LOGFILE_INST 2>&1

./$FILE_SCRIPT_OSMDATA >> $LOGFILE_INST 2>&1
./$FILE_POSTGRE_PATCH >> $LOGFILE_INST 2>&1
./$FILE_POSTGRE_DB >> $LOGFILE_INST 2>&1
./$SCRIPT_OSM2PGSQL >> $LOGFILE_INST 2>&1
./$SCRIPT_MAPNIK_TOOLS >> $LOGFILE_INST 2>&1
./$SCRIPT_MAPNIK_TILES >> $LOGFILE_INST 2>&1





